### ISSUE TITLE
There is no scrollbar in quick-actions menu

### ISSUE THREAD

**Issue by EdaDeniz** [app-generator/django-dashboard-atlantis-dark#4]
I am using this theme. I added a lot of quick action item to Quick Actions menu on the navigation. But there is no scrollbar and not showing all content. How can I fix it?

```
<div class="dropdown-menu quick-actions quick-actions-info animated fadeIn">
<div class="quick-actions-header">
   <span class="title mb-1">Quick Actions</span>
   <span class="subtitle op-8">Shortcuts</span>
</div>
<div class="quick-actions-scroll scrollbar-outer">
<div class="quick-actions-items">
<div class="row m-0">
<a class="col-6 col-md-4 p-0" href="{% url 'home' %}">
   <div class="quick-actions-item">
      <i class="flaticon-home"></i>
      <span class="text">
         Dashboard
         <p></p>
      </span>
   </div>
</a>
.....
```

**Comment by app-generator** [comment]
Hello @EdaDeniz, 

Thank you for using this kit. Can you provide more information, please?
Not sure if the reported topic is an issue or an enhancement. 

P.S. A screenshot sometimes helps.

**Comment by EdaDeniz** [comment]
Hello @app-generator ,
 When I asked your Discord channel, they asked me to write it here.
This is a screenshot from my project. 

![image](https://user-images.githubusercontent.com/42175967/117832873-8ad88080-b27e-11eb-95ac-bb6f0f1b146c.png)

As you can see from here, as the list goes on, it takes up the screen and it is cut off because there is no scrollbar.
