### ISSUE TITLE
Multiple Select Doesn't Work

### ISSUE THREAD

**Issue by a-wip0** [app-generator/django-dashboard-atlantis-dark#5]
![image](https://user-images.githubusercontent.com/33978908/118840288-76852b00-b8f1-11eb-9fc3-7cf60d239f2f.png)

I can only pick one option

**Comment by app-generator** [comment]
Hello @a-wip0, 

Thank you for using our products. 
Please hold the control key (on Windows Systems) to select more items.  

The mentioned control works as expected.
